### ISSUE TITLE
Préférable

### ISSUE THREAD

**Issue by pascalfares** [majedlb/Neo4j#1]
Mettre ceci Document de Neo4j.docx dans le wiki https://github.com/majedlb/Neo4j/wiki

**Comment by majedlb** [comment]
Cher Dr. Pascal Fares,

J'ai mis le Document de Neo4j dans wiki.

Lien vers mon projet SMB214 sur Github dans le wiki:
https://github.com/majedlb/Neo4j/wiki
S'il y a quelque chose qui n'est pas correcte veuillez clarifier cela svp.

Je vous remercie pour votre temps

2016-06-28 8:54 GMT+03:00 Pascal Fares notifications@github.com:

**Comment by pascalfares** [comment]
185.81.140.88
